const techTerms = [
  { word: "Abstract", pronunciation: "Éb-strékt", meaning: "Conceito que define estrutura sem implementação concreta" },
  { word: "Access Token", pronunciation: "Ék-ses Tô-ken", meaning: "Chave temporária usada para autenticar requisições" },
  { word: "Agile", pronunciation: "Éi-djil", meaning: "Metodologia de desenvolvimento de software iterativo e incremental" },
  { word: "AJAX", pronunciation: "Éi-djéks", meaning: "Técnica para fazer requisições ao servidor sem recarregar a página" },
  { word: "Algorithm", pronunciation: "Él-go-ri-dhêm", meaning: "Sequência de passos definidos para resolver um problema" },
  { word: "Alias", pronunciation: "Éi-li-es", meaning: "Nome alternativo para um comando, variável ou rota" },
  { word: "Alpha", pronunciation: "Él-fê", meaning: "Versão inicial e instável de um software, ainda em desenvolvimento" },
  { word: "Analytics", pronunciation: "É-ne-lí-tiks", meaning: "Análise e interpretação de dados e métricas de uso" },
  { word: "Android", pronunciation: "Én-droid", meaning: "Sistema operacional mobile desenvolvido pelo Google" },
  { word: "Angular", pronunciation: "Én-guiú-ler", meaning: "Framework JavaScript mantido pelo Google para criar SPAs" },
  { word: "Annotation", pronunciation: "É-no-téi-shen", meaning: "Metadado adicionado ao código para configuração ou documentação" },
  { word: "Anti-pattern", pronunciation: "Én-ti-pé-tern", meaning: "Solução ineficiente que parece boa mas cria problemas" },
  { word: "Apache", pronunciation: "Ê-pé-chi", meaning: "Servidor web open source amplamente utilizado no mundo" },
  { word: "API", pronunciation: "Éi-Pí-Ái", meaning: "Interface de Programação de Aplicações — contrato entre sistemas" },
  { word: "App", pronunciation: "Ép", meaning: "Aplicativo de software, geralmente mobile ou web" },
  { word: "Append", pronunciation: "Ê-pênd", meaning: "Adicionar dados ao final de uma lista, arquivo ou string" },
  { word: "Archive", pronunciation: "Ár-kaiv", meaning: "Arquivo comprimido ou repositório de dados históricos" },
  { word: "Arduino", pronunciation: "Ár-duí-no", meaning: "Plataforma open source de prototipagem eletrônica" },
  { word: "Array", pronunciation: "Ê-rréi", meaning: "Estrutura de dados que armazena lista ordenada de elementos" },
  { word: "ASCII", pronunciation: "Ésk-i", meaning: "Padrão de codificação de caracteres em números" },
  { word: "Assembly", pronunciation: "Ê-sêm-bli", meaning: "Linguagem de programação de baixo nível próxima ao hardware" },
  { word: "Assertion", pronunciation: "Ê-sêr-shen", meaning: "Verificação que garante que uma condição é verdadeira nos testes" },
  { word: "Async", pronunciation: "Éi-sink", meaning: "Operação assíncrona que não bloqueia a execução do programa" },
  { word: "Async/Await", pronunciation: "Éi-sink / Ê-uéit", meaning: "Padrão moderno para escrever código assíncrono de forma legível" },
  { word: "Atomic", pronunciation: "Ê-tô-mik", meaning: "Operação indivisível que ocorre por completo ou não ocorre" },
  { word: "Authentication", pronunciation: "Ô-then-ti-kéi-shen", meaning: "Processo de verificar a identidade de um usuário ou sistema" },
  { word: "Authorization", pronunciation: "Ô-tho-ri-zéi-shen", meaning: "Processo de conceder ou negar permissões de acesso" },
  { word: "Automation", pronunciation: "Ô-to-méi-shen", meaning: "Execução automática de tarefas sem intervenção humana" },
  { word: "Avatar", pronunciation: "Éi-ve-tár", meaning: "Representação visual de um usuário em plataformas digitais" },
  { word: "AWS", pronunciation: "Éi-Dâb-iú-És", meaning: "Amazon Web Services — plataforma de computação em nuvem da Amazon" },
  { word: "Axios", pronunciation: "Ék-si-ós", meaning: "Biblioteca JavaScript para fazer requisições HTTP" },
  { word: "Azure", pronunciation: "É-jorr", meaning: "Plataforma de computação em nuvem da Microsoft" },
  { word: "Backend", pronunciation: "Béck-ênd", meaning: "Parte do servidor de uma aplicação que processa dados e lógica" },
  { word: "Backlog", pronunciation: "Béck-lóg", meaning: "Lista de tarefas e funcionalidades pendentes de um projeto" },
  { word: "Backup", pronunciation: "Béck-ãp", meaning: "Cópia de segurança de dados para recuperação em caso de falha" },
  { word: "Badge", pronunciation: "Béidj", meaning: "Emblema visual indicador de status ou conquista" },
  { word: "Bandwidth", pronunciation: "Bénd-uídth", meaning: "Quantidade de dados que pode ser transmitida em um período" },
  { word: "Base64", pronunciation: "Béis-Sík-sti-fôr", meaning: "Esquema de codificação que representa dados binários em texto" },
  { word: "Bash", pronunciation: "Bésh", meaning: "Shell padrão do Linux para executar comandos no terminal" },
  { word: "Batch", pronunciation: "Bétch", meaning: "Processamento de um conjunto de dados em lote, sem interação" },
  { word: "Beacon", pronunciation: "Bí-ken", meaning: "Sinal de rastreamento enviado para coletar dados de usuário" },
  { word: "Benchmark", pronunciation: "Bênch-márk", meaning: "Teste de desempenho comparativo entre sistemas ou versões" },
  { word: "Beta", pronunciation: "Béi-tê", meaning: "Versão de teste de software disponível para usuários selecionados" },
  { word: "Binary", pronunciation: "Bái-nê-ri", meaning: "Sistema numérico de base 2 usando apenas 0 e 1" },
  { word: "Binding", pronunciation: "Bái-ndin", meaning: "Conexão entre um dado e um elemento da interface" },
  { word: "Bitcoin", pronunciation: "Bít-koin", meaning: "Criptomoeda digital descentralizada baseada em blockchain" },
  { word: "Bitbucket", pronunciation: "Bít-bâ-ket", meaning: "Plataforma de hospedagem de código com suporte a Git" },
  { word: "Bitwise", pronunciation: "Bít-uáiz", meaning: "Operações realizadas a nível de bits individuais" },
  { word: "Blockchain", pronunciation: "Blók-chein", meaning: "Tecnologia de registro distribuído e imutável de transações" },
  { word: "Blog", pronunciation: "Blóg", meaning: "Diário digital com publicações periódicas de conteúdo" },
  { word: "Boilerplate", pronunciation: "Bói-ler-pleit", meaning: "Código padrão repetitivo usado como base inicial de projetos" },
  { word: "Boolean", pronunciation: "Bú-li-en", meaning: "Tipo de dado que representa apenas verdadeiro ou falso" },
  { word: "Bootstrap", pronunciation: "Bút-stréip", meaning: "Framework CSS popular para criar interfaces responsivas rapidamente" },
  { word: "Branch", pronunciation: "Brénch", meaning: "Ramificação independente no controle de versão do código" },
  { word: "Breakpoint", pronunciation: "Bréik-point", meaning: "Ponto de pausa no código para depuração ou breakpoint CSS" },
  { word: "Browser", pronunciation: "Bráu-zer", meaning: "Navegador web como Chrome, Firefox ou Safari" },
  { word: "Buffer", pronunciation: "Bâ-fer", meaning: "Área temporária de memória para armazenar dados em trânsito" },
  { word: "Bug", pronunciation: "Bãg", meaning: "Erro ou falha no código que causa comportamento inesperado" },
  { word: "Build", pronunciation: "Bíld", meaning: "Processo de compilar e preparar código para execução ou deploy" },
  { word: "Bundle", pronunciation: "Bân-del", meaning: "Pacote de arquivos agrupados e otimizados para produção" },
  { word: "Bytecode", pronunciation: "Báit-kôd", meaning: "Código intermediário compilado interpretado pela máquina virtual" },
  { word: "Cache", pronunciation: "Kéch", meaning: "Armazenamento temporário de dados para acesso mais rápido" },
  { word: "Cache Invalidation", pronunciation: "Kéch In-vé-li-déi-shen", meaning: "Processo de remover ou atualizar dados desatualizados no cache" },
  { word: "Caching", pronunciation: "Ké-shin", meaning: "Técnica de armazenar resultados para evitar reprocessamento" },
  { word: "Callback", pronunciation: "Kól-béck", meaning: "Função passada como argumento para ser chamada após outra terminar" },
  { word: "Callback Hell", pronunciation: "Kól-béck Hêl", meaning: "Encadeamento excessivo de callbacks tornando o código ilegível" },
  { word: "Canvas", pronunciation: "Kén-ves", meaning: "Elemento HTML usado para desenhar gráficos via JavaScript" },
  { word: "Cascade", pronunciation: "Kés-kéid", meaning: "Aplicação em cascata de estilos no CSS" },
  { word: "CDN", pronunciation: "Sí-Dí-Én", meaning: "Rede de Distribuição de Conteúdo para entrega rápida de arquivos" },
  { word: "Certificate", pronunciation: "Ser-tí-fi-keit", meaning: "Certificado digital que valida a identidade de um site ou serviço" },
  { word: "Changelog", pronunciation: "Chéindj-lóg", meaning: "Registro cronológico das mudanças entre versões de um software" },
  { word: "Character", pronunciation: "Ké-rik-ter", meaning: "Símbolo ou letra individual em uma string de texto" },
  { word: "Chatbot", pronunciation: "Chét-bót", meaning: "Robô de conversação automatizado que responde mensagens" },
  { word: "Checksum", pronunciation: "Chék-sâm", meaning: "Valor calculado para verificar a integridade de dados" },
  { word: "Chunk", pronunciation: "Chânk", meaning: "Pedaço ou fragmento de dados processado de forma incremental" },
  { word: "CI/CD", pronunciation: "Sí-Ái / Sí-Dí", meaning: "Integração e Entrega Contínua — automação do fluxo de deploy" },
  { word: "Circuit Breaker", pronunciation: "Sêr-kit Bréi-ker", meaning: "Padrão que interrompe chamadas a serviços com falha" },
  { word: "Class", pronunciation: "Kléss", meaning: "Modelo ou molde para criar objetos em programação orientada a objetos" },
  { word: "CLI", pronunciation: "Sí-El-Ái", meaning: "Interface de Linha de Comando para interagir com o sistema via texto" },
  { word: "Client", pronunciation: "Kláient", meaning: "Dispositivo ou aplicação que consome serviços de um servidor" },
  { word: "Client-Side", pronunciation: "Kláient-Sáid", meaning: "Código executado no navegador do usuário, não no servidor" },
  { word: "Clone", pronunciation: "Klôn", meaning: "Cópia completa de um repositório ou objeto" },
  { word: "Closure", pronunciation: "Klô-zher", meaning: "Função que mantém acesso ao escopo onde foi criada" },
  { word: "Cloud", pronunciation: "Kláud", meaning: "Computação em nuvem — serviços de infraestrutura pela internet" },
  { word: "Cluster", pronunciation: "Klâs-ter", meaning: "Grupo de servidores que trabalham juntos como uma unidade" },
  { word: "CMS", pronunciation: "Sí-Êm-És", meaning: "Sistema de Gerenciamento de Conteúdo como WordPress" },
  { word: "Code", pronunciation: "Kôd", meaning: "Conjunto de instruções escritas em uma linguagem de programação" },
  { word: "Commit", pronunciation: "Ko-mít", meaning: "Salvar permanentemente um conjunto de mudanças no repositório" },
  { word: "Compile", pronunciation: "Kom-páil", meaning: "Transformar código-fonte em código executável pelo computador" },
  { word: "Compiler", pronunciation: "Kom-pái-ler", meaning: "Programa que traduz código de alto nível para código de máquina" },
  { word: "Component", pronunciation: "Kom-pô-nent", meaning: "Parte reutilizável e independente de uma interface" },
  { word: "Concatenation", pronunciation: "Kon-ké-te-néi-shen", meaning: "Operação de unir duas ou mais strings em uma só" },
  { word: "Concurrency", pronunciation: "Kon-kâ-ren-si", meaning: "Execução de múltiplas tarefas ao mesmo tempo ou intercalada" },
  { word: "Config", pronunciation: "Kon-fíg", meaning: "Arquivo ou conjunto de configurações de um sistema" },
  { word: "Conflict", pronunciation: "Kón-flikt", meaning: "Colisão de mudanças incompatíveis em um merge de código" },
  { word: "Console", pronunciation: "Kón-sôl", meaning: "Terminal de saída de mensagens de depuração" },
  { word: "Constant", pronunciation: "Kón-stent", meaning: "Valor imutável declarado no código que não pode ser alterado" },
  { word: "Constructor", pronunciation: "Kon-strâk-ter", meaning: "Método especial chamado automaticamente ao criar um objeto" },
  { word: "Container", pronunciation: "Kon-téiner", meaning: "Ambiente isolado e portátil para executar aplicações" },
  { word: "Context", pronunciation: "Kón-tekst", meaning: "Ambiente, estado ou escopo atual de execução" },
  { word: "Controller", pronunciation: "Kon-trô-ler", meaning: "Componente que gerencia a lógica entre a view e o modelo" },
  { word: "Cookie", pronunciation: "Kú-ki", meaning: "Pequeno dado armazenado no navegador pelo servidor" },
  { word: "Coroutine", pronunciation: "Kó-ro-tin", meaning: "Função que pode ser pausada e retomada em pontos específicos" },
  { word: "Crash", pronunciation: "Krésh", meaning: "Falha crítica que encerra abruptamente um programa" },
  { word: "Credentials", pronunciation: "Kri-dén-shels", meaning: "Informações de autenticação como usuário e senha" },
  { word: "Cron", pronunciation: "Krón", meaning: "Agendador de tarefas para execução periódica no sistema" },
  { word: "Cross-Origin", pronunciation: "Krós-Ó-ri-djin", meaning: "Requisição feita de um domínio para outro diferente" },
  { word: "CRUD", pronunciation: "Krúd", meaning: "Create, Read, Update, Delete — operações básicas em banco de dados" },
  { word: "Cryptography", pronunciation: "Krip-tó-gre-fi", meaning: "Ciência de proteger informações através de criptografia" },
  { word: "CSS", pronunciation: "Sí-És-És", meaning: "Cascading Style Sheets — linguagem para estilizar páginas web" },
  { word: "Cursor", pronunciation: "Kêr-ser", meaning: "Ponteiro na tela ou objeto que percorre resultados de banco" },
  { word: "Custom Hook", pronunciation: "Kâs-tem Húk", meaning: "Hook personalizado reutilizável criado no React" },
  { word: "Daemon", pronunciation: "Díi-men", meaning: "Processo que roda em segundo plano no sistema operacional" },
  { word: "Dashboard", pronunciation: "Désh-bord", meaning: "Painel visual que exibe informações e métricas importantes" },
  { word: "Data", pronunciation: "Déi-te", meaning: "Informações brutas processadas por um sistema" },
  { word: "Data Lake", pronunciation: "Déi-te Léik", meaning: "Repositório centralizado que armazena dados brutos em escala" },
  { word: "Data Pipeline", pronunciation: "Déi-te Páip-lain", meaning: "Fluxo automatizado de processamento e transporte de dados" },
  { word: "Data Structure", pronunciation: "Déi-te Strâk-cher", meaning: "Forma organizada de armazenar e acessar dados na memória" },
  { word: "Database", pronunciation: "Déi-te-beis", meaning: "Sistema organizado para armazenar e consultar dados" },
  { word: "Deadlock", pronunciation: "Déd-lók", meaning: "Situação onde dois processos se bloqueiam mutuamente para sempre" },
  { word: "Debug", pronunciation: "Di-bãg", meaning: "Processo de encontrar e corrigir erros em um programa" },
  { word: "Debugging", pronunciation: "Di-bã-guin", meaning: "Atividade de identificar, analisar e corrigir bugs no código" },
  { word: "Debounce", pronunciation: "Di-báuns", meaning: "Técnica que atrasa a execução até parar de receber eventos" },
  { word: "Decoupling", pronunciation: "Di-kâ-plin", meaning: "Redução da dependência entre módulos para maior flexibilidade" },
  { word: "Default", pronunciation: "Di-fólt", meaning: "Valor ou comportamento padrão quando nenhum é especificado" },
  { word: "Delegation", pronunciation: "Dé-le-guéi-shen", meaning: "Transferência de responsabilidade de um objeto para outro" },
  { word: "Deploy", pronunciation: "Di-plói", meaning: "Publicar e disponibilizar uma aplicação em um servidor" },
  { word: "Dependency", pronunciation: "Di-pên-den-si", meaning: "Biblioteca ou módulo externo necessário para o projeto funcionar" },
  { word: "Deprecated", pronunciation: "Dé-pre-kéi-ted", meaning: "Recurso obsoleto que será removido em versões futuras" },
  { word: "Deserialization", pronunciation: "Di-si-ri-e-li-zéi-shen", meaning: "Converter dados serializados de volta em um objeto utilizável" },
  { word: "Design", pronunciation: "Di-záin", meaning: "Projeto visual ou estrutural de um sistema ou interface" },
  { word: "Desktop App", pronunciation: "Dés-tóp Ép", meaning: "Aplicação instalada e executada diretamente no computador" },
  { word: "Destructor", pronunciation: "Dis-trâk-ter", meaning: "Método chamado automaticamente ao destruir um objeto" },
  { word: "Destructuring", pronunciation: "Di-strâk-che-rin", meaning: "Sintaxe para extrair valores de arrays ou objetos facilmente" },
  { word: "DevOps", pronunciation: "Dév-Óps", meaning: "Cultura que integra desenvolvimento e operações de TI" },
  { word: "DevTools", pronunciation: "Dév-Túls", meaning: "Ferramentas de desenvolvimento integradas nos navegadores" },
  { word: "Diff", pronunciation: "Díf", meaning: "Diferença entre duas versões de um arquivo de código" },
  { word: "Distributed System", pronunciation: "Dis-tri-biú-ted Sís-tem", meaning: "Sistema espalhado por múltiplos nós que trabalham juntos" },
  { word: "DNS", pronunciation: "Dí-Én-És", meaning: "Sistema de Nomes de Domínio — traduz URLs em endereços IP" },
  { word: "Docker", pronunciation: "Dó-ker", meaning: "Plataforma para criar, distribuir e executar containers" },
  { word: "Docker Compose", pronunciation: "Dó-ker Kom-pôz", meaning: "Ferramenta para orquestrar múltiplos containers Docker" },
  { word: "DOM", pronunciation: "Dóm", meaning: "Document Object Model — representação da estrutura HTML em memória" },
  { word: "Domain", pronunciation: "Do-méin", meaning: "Endereço identificador de um site na internet" },
  { word: "Download", pronunciation: "Dáun-lôd", meaning: "Transferir um arquivo de um servidor para o dispositivo local" },
  { word: "Drag", pronunciation: "Drég", meaning: "Arrastar um elemento na tela com o mouse ou toque" },
  { word: "Driver", pronunciation: "Dráiver", meaning: "Software que permite o sistema operacional controlar um hardware" },
  { word: "Drop", pronunciation: "Dróp", meaning: "Soltar um elemento arrastado ou excluir dados do banco" },
  { word: "Dropdown", pronunciation: "Dróp-dáun", meaning: "Menu que se expande ao ser clicado, mostrando opções" },
  { word: "DRY", pronunciation: "Dí-Ár-Uái", meaning: "Don't Repeat Yourself — princípio de não duplicar código" },
  { word: "Duck Typing", pronunciation: "Dâk Táip-in", meaning: "Tipagem baseada no comportamento do objeto, não no seu tipo" },
  { word: "Dynamic", pronunciation: "Dai-né-mik", meaning: "Conteúdo ou comportamento gerado em tempo real de execução" },
  { word: "Eager Loading", pronunciation: "Í-guer Lô-din", meaning: "Carregamento antecipado de dados relacionados em uma consulta" },
  { word: "Edge Case", pronunciation: "Édj Kéis", meaning: "Caso extremo ou limite que pode causar comportamento inesperado" },
  { word: "Elasticsearch", pronunciation: "I-lés-tik-sertch", meaning: "Motor de busca e análise de dados em tempo real" },
  { word: "Encapsulation", pronunciation: "En-kép-sel-éi-shen", meaning: "Ocultar os detalhes internos de um objeto, expondo apenas o necessário" },
  { word: "Endpoint", pronunciation: "Énd-point", meaning: "URL específica de uma API que responde a uma requisição" },
  { word: "Enum", pronunciation: "Í-nêm", meaning: "Conjunto de constantes nomeadas representando valores possíveis" },
  { word: "Environment", pronunciation: "En-váiren-ment", meaning: "Conjunto de configurações e variáveis onde o código é executado" },
  { word: "Error", pronunciation: "É-ror", meaning: "Mensagem que indica uma falha ou problema na execução" },
  { word: "ESLint", pronunciation: "Í-És-Lint", meaning: "Ferramenta de análise estática para detectar problemas no JavaScript" },
  { word: "Event", pronunciation: "I-vênt", meaning: "Ação ou ocorrência que dispara uma função no sistema" },
  { word: "Event Driven", pronunciation: "I-vênt Drí-ven", meaning: "Arquitetura onde o fluxo é controlado por eventos" },
  { word: "Event Emitter", pronunciation: "I-vênt I-mí-ter", meaning: "Objeto que emite e gerencia eventos para outros ouvirem" },
  { word: "Event Loop", pronunciation: "I-vênt Lúp", meaning: "Ciclo que processa eventos e executa callbacks no JavaScript" },
  { word: "Exception", pronunciation: "Êk-sép-shen", meaning: "Erro tratável que interrompe o fluxo normal de execução" },
  { word: "Expression", pronunciation: "Êks-préi-shen", meaning: "Trecho de código que é avaliado e retorna um valor" },
  { word: "Extension", pronunciation: "Êks-tên-shen", meaning: "Complemento que adiciona funcionalidades a um software" },
  { word: "Factory", pronunciation: "Fék-te-ri", meaning: "Padrão de criação que centraliza a instanciação de objetos" },
  { word: "Fallback", pronunciation: "Fól-béck", meaning: "Alternativa usada quando a opção principal falha" },
  { word: "Favicon", pronunciation: "Fé-vi-kón", meaning: "Pequeno ícone exibido na aba do navegador de um site" },
  { word: "Feature", pronunciation: "Fí-cher", meaning: "Funcionalidade ou recurso de um software" },
  { word: "Feature Flag", pronunciation: "Fí-cher Flég", meaning: "Mecanismo para ativar ou desativar recursos sem fazer deploy" },
  { word: "Fetch", pronunciation: "Fétch", meaning: "Buscar dados de uma API ou servidor pela internet" },
  { word: "Fiber", pronunciation: "Fái-ber", meaning: "Unidade leve de execução para concorrência eficiente" },
  { word: "File", pronunciation: "Fáil", meaning: "Arquivo digital que armazena dados ou código" },
  { word: "Filter", pronunciation: "Fíl-ter", meaning: "Função que seleciona elementos que atendem a uma condição" },
  { word: "Firestore", pronunciation: "Fáier-stôr", meaning: "Banco de dados NoSQL em tempo real da Google Firebase" },
  { word: "Firewall", pronunciation: "Fáier-uól", meaning: "Barreira de segurança que controla tráfego de rede" },
  { word: "Flag", pronunciation: "Flég", meaning: "Marcador booleano ou parâmetro que ativa um comportamento" },
  { word: "Float", pronunciation: "Flôt", meaning: "Tipo numérico com ponto decimal ou posicionamento CSS" },
  { word: "Flux", pronunciation: "Flâks", meaning: "Arquitetura de fluxo unidirecional de dados em aplicações React" },
  { word: "Folder", pronunciation: "Fôl-der", meaning: "Diretório que organiza e agrupa arquivos" },
  { word: "Fork", pronunciation: "Fórk", meaning: "Cópia independente de um repositório para desenvolvimento separado" },
  { word: "Format", pronunciation: "Fór-mét", meaning: "Estrutura ou padrão de organização de dados" },
  { word: "Formatter", pronunciation: "Fór-me-ter", meaning: "Ferramenta que formata automaticamente o código-fonte" },
  { word: "Framework", pronunciation: "Fréim-uérk", meaning: "Estrutura base com convenções para acelerar o desenvolvimento" },
  { word: "Frontend", pronunciation: "Frônt-ênd", meaning: "Parte visual de uma aplicação com que o usuário interage" },
  { word: "Function", pronunciation: "Fânk-shen", meaning: "Bloco de código reutilizável que realiza uma tarefa específica" },
  { word: "Functional Programming", pronunciation: "Fânk-she-nel Prô-gre-min", meaning: "Paradigma baseado em funções puras sem efeitos colaterais" },
  { word: "Fullstack", pronunciation: "Fúl-stéck", meaning: "Desenvolvimento completo abrangendo frontend e backend" },
  { word: "Garbage Collection", pronunciation: "Gár-bidj Ko-lék-shen", meaning: "Limpeza automática de memória não utilizada pelo programa" },
  { word: "Gateway", pronunciation: "Guéit-uéi", meaning: "Ponto de entrada e roteamento de requisições em uma API" },
  { word: "Generator", pronunciation: "Djê-ne-réi-ter", meaning: "Função especial que produz valores sob demanda, um por vez" },
  { word: "Git", pronunciation: "Guít", meaning: "Sistema de controle de versão distribuído para código-fonte" },
  { word: "Git Flow", pronunciation: "Guít Flô", meaning: "Fluxo de trabalho padronizado com branches para Git" },
  { word: "Git Stash", pronunciation: "Guít Stésh", meaning: "Salvar mudanças temporariamente sem fazer commit" },
  { word: "GitHub", pronunciation: "Guít-hâb", meaning: "Plataforma online para hospedar e colaborar em código com Git" },
  { word: "Global State", pronunciation: "Glô-bel Stéit", meaning: "Estado acessível por toda a aplicação, não apenas localmente" },
  { word: "GPU", pronunciation: "Djí-Pí-iú", meaning: "Unidade de Processamento Gráfico para cálculos paralelos" },
  { word: "Graceful Degradation", pronunciation: "Gréis-fel Di-gre-déi-shen", meaning: "Garantir funcionalidade básica mesmo quando recursos falham" },
  { word: "GraphQL", pronunciation: "Gréf-Kiú-Él", meaning: "Linguagem de consulta para APIs com resposta precisa dos dados" },
  { word: "GraphQL Schema", pronunciation: "Gréf-Kiú-Él Skí-me", meaning: "Definição formal dos tipos e operações disponíveis no GraphQL" },
  { word: "Grid", pronunciation: "Gríd", meaning: "Sistema de grade CSS para criação de layouts bidimensionais" },
  { word: "gRPC", pronunciation: "Djí-Ár-Pí-Sí", meaning: "Framework de chamada remota de procedimento de alto desempenho" },
  { word: "Guard", pronunciation: "Gárd", meaning: "Proteção ou verificação de acesso a rotas e recursos" },
  { word: "Hack", pronunciation: "Hék", meaning: "Solução criativa ou invasão não autorizada em sistema" },
  { word: "Handler", pronunciation: "Hénd-ler", meaning: "Função responsável por tratar um evento ou requisição" },
  { word: "Hardware", pronunciation: "Hárd-uér", meaning: "Componentes físicos do computador como processador e memória" },
  { word: "Hash", pronunciation: "Hésh", meaning: "Função que gera código único de tamanho fixo a partir de dados" },
  { word: "Hash Map", pronunciation: "Hésh Méip", meaning: "Estrutura de dados que mapeia chaves a valores com acesso rápido" },
  { word: "Header", pronunciation: "Hé-der", meaning: "Cabeçalho de um arquivo, página ou requisição HTTP" },
  { word: "Headless", pronunciation: "Héd-les", meaning: "Software ou CMS sem interface gráfica própria" },
  { word: "Heap", pronunciation: "Híp", meaning: "Área de memória usada para alocação dinâmica de objetos" },
  { word: "Heroku", pronunciation: "Hé-ro-ku", meaning: "Plataforma de hospedagem em nuvem focada em simplicidade" },
  { word: "Heuristic", pronunciation: "Hiú-rís-tik", meaning: "Abordagem de resolução baseada em experiência prática" },
  { word: "High Availability", pronunciation: "Hái Ê-véi-le-bí-li-ti", meaning: "Garantia de que um sistema está sempre disponível para uso" },
  { word: "Hook", pronunciation: "Húk", meaning: "Função que se conecta a eventos do ciclo de vida (ex: React Hooks)" },
  { word: "Host", pronunciation: "Hôst", meaning: "Servidor ou domínio que hospeda uma aplicação ou site" },
  { word: "Hot Reload", pronunciation: "Hót Ri-lôd", meaning: "Atualizar a aplicação automaticamente sem reiniciar o servidor" },
  { word: "Hotfix", pronunciation: "Hót-fíks", meaning: "Correção urgente aplicada diretamente em produção" },
  { word: "HTML", pronunciation: "Éich-Tí-Êm-Él", meaning: "HyperText Markup Language — linguagem de marcação para web" },
  { word: "HTTP", pronunciation: "Éich-Tí-Tí-Pí", meaning: "Protocolo de transferência de dados para comunicação web" },
  { word: "HTTP/2", pronunciation: "Éich-Tí-Tí-Pí Tú", meaning: "Versão mais rápida e eficiente do protocolo HTTP" },
  { word: "HTTPS", pronunciation: "Éich-Tí-Tí-Pí-És", meaning: "HTTP com camada de segurança SSL/TLS para criptografia" },
  { word: "Hydration", pronunciation: "Hai-dréi-shen", meaning: "Processo de ativar o JavaScript em HTML pré-renderizado" },
  { word: "Hyperlink", pronunciation: "Hái-per-link", meaning: "Link clicável que navega para outra página ou recurso" },
  { word: "Icon", pronunciation: "Ái-kon", meaning: "Imagem simbólica pequena que representa uma ação ou conteúdo" },
  { word: "IDE", pronunciation: "Ái-Dí-Í", meaning: "Ambiente de Desenvolvimento Integrado com editor e ferramentas" },
  { word: "Idempotent", pronunciation: "Ai-dêm-po-tent", meaning: "Operação que produz o mesmo resultado independente de quantas vezes é chamada" },
  { word: "Idiomatic", pronunciation: "Í-di-o-mé-tik", meaning: "Código que segue as convenções e estilo natural da linguagem" },
  { word: "Image", pronunciation: "Í-midjê", meaning: "Arquivo de imagem digital ou snapshot de um container" },
  { word: "Immutable", pronunciation: "I-miú-te-bel", meaning: "Dado que não pode ser modificado após ser criado" },
  { word: "Import", pronunciation: "Im-port", meaning: "Carregar um módulo ou arquivo externo no código atual" },
  { word: "Index", pronunciation: "Ín-deks", meaning: "Índice de banco de dados ou página inicial de um site" },
  { word: "Inheritance", pronunciation: "In-hé-ri-tens", meaning: "Mecanismo onde uma classe herda propriedades de outra" },
  { word: "Infrastructure", pronunciation: "Ín-fre-strâk-cher", meaning: "Base tecnológica de servidores, redes e serviços de TI" },
  { word: "Injection", pronunciation: "In-djék-shen", meaning: "Inserção de código ou dados maliciosos em um sistema" },
  { word: "Inline", pronunciation: "In-láin", meaning: "Estilo ou elemento aplicado diretamente na mesma linha" },
  { word: "Input", pronunciation: "Ín-put", meaning: "Dado inserido pelo usuário ou recebido por uma função" },
  { word: "Instance", pronunciation: "Ín-stens", meaning: "Objeto criado a partir de uma classe ou template" },
  { word: "Integer", pronunciation: "Ín-ti-djer", meaning: "Número inteiro sem parte decimal no código" },
  { word: "Integration", pronunciation: "Ín-ti-gréi-shen", meaning: "Conexão e comunicação entre diferentes sistemas ou módulos" },
  { word: "Integration Test", pronunciation: "Ín-ti-gréi-shen Tést", meaning: "Teste que verifica a interação entre múltiplos módulos" },
  { word: "Interface", pronunciation: "Ín-ter-feis", meaning: "Contrato que define quais métodos um objeto deve implementar" },
  { word: "Internet", pronunciation: "Ín-ter-nét", meaning: "Rede mundial de computadores interconectados" },
  { word: "IoT", pronunciation: "Ái-Ô-Tí", meaning: "Internet das Coisas — dispositivos físicos conectados à internet" },
  { word: "IP", pronunciation: "Ái-Pí", meaning: "Internet Protocol — endereço único que identifica um dispositivo na rede" },
  { word: "Iterator", pronunciation: "Í-te-réi-ter", meaning: "Objeto que permite percorrer uma coleção elemento por elemento" },
  { word: "JavaScript", pronunciation: "Djá-va-skrípt", meaning: "Linguagem de programação principal da web, roda no navegador" },
  { word: "JSON", pronunciation: "Djéi-Son", meaning: "Formato leve de troca de dados baseado em texto legível" },
  { word: "JWT", pronunciation: "Djéi-Dâb-iú-Tí", meaning: "JSON Web Token — padrão para transmitir informações de autenticação" },
  { word: "Kernel", pronunciation: "Kêr-nel", meaning: "Núcleo do sistema operacional que gerencia hardware e processos" },
  { word: "Keyboard", pronunciation: "Kí-bord", meaning: "Dispositivo de entrada com teclas para digitar comandos" },
  { word: "Kubernetes", pronunciation: "Kiú-ber-né-tis", meaning: "Plataforma de orquestração de containers em escala" },
  { word: "Lambda", pronunciation: "Lém-bde", meaning: "Função anônima ou serviço serverless da AWS" },
  { word: "Latency", pronunciation: "Léi-ten-si", meaning: "Tempo de resposta ou atraso em uma operação de rede" },
  { word: "Layout", pronunciation: "Léi-áut", meaning: "Disposição e organização visual dos elementos na tela" },
  { word: "Lazy Evaluation", pronunciation: "Léi-zi I-vé-liú-éi-shen", meaning: "Avaliar uma expressão somente quando seu valor é necessário" },
  { word: "Lazy Loading", pronunciation: "Léi-zi Lô-din", meaning: "Carregar recursos somente quando forem necessários" },
  { word: "Library", pronunciation: "Lái-bre-ri", meaning: "Conjunto de funções e utilidades reutilizáveis para desenvolvedores" },
  { word: "Link", pronunciation: "Línk", meaning: "Hiperlink ou referência para outro recurso ou arquivo" },
  { word: "Linter", pronunciation: "Lín-ter", meaning: "Ferramenta que analisa o código e aponta erros e más práticas" },
  { word: "Linux", pronunciation: "Lí-nâks", meaning: "Sistema operacional open source baseado em Unix" },
  { word: "Load", pronunciation: "Lôd", meaning: "Carregar dados, arquivos ou medir quantidade de requisições" },
  { word: "Load Balancer", pronunciation: "Lôd Bé-len-ser", meaning: "Distribui requisições entre múltiplos servidores para balancear carga" },
  { word: "Local Storage", pronunciation: "Lô-kel Stô-ridjê", meaning: "Armazenamento persistente no navegador acessível via JavaScript" },
  { word: "Log", pronunciation: "Lóg", meaning: "Registro de eventos, erros e ações de um sistema" },
  { word: "Login", pronunciation: "Lóg-in", meaning: "Processo de entrada e autenticação em um sistema" },
  { word: "Logging", pronunciation: "Lóg-in", meaning: "Prática de registrar eventos e informações do sistema" },
  { word: "Logout", pronunciation: "Lóg-áut", meaning: "Processo de sair e encerrar sessão em um sistema" },
  { word: "Loop", pronunciation: "Lúp", meaning: "Estrutura de repetição que executa código múltiplas vezes" },
  { word: "Manifest", pronunciation: "Mé-ni-fest", meaning: "Arquivo de configuração que descreve uma aplicação ou seus recursos" },
  { word: "Map", pronunciation: "Méip", meaning: "Estrutura de dados chave-valor ou função que transforma arrays" },
  { word: "Markup", pronunciation: "Már-kâp", meaning: "Linguagem de marcação como HTML para estruturar documentos" },
  { word: "Memory Leak", pronunciation: "Mé-me-ri Lík", meaning: "Falha onde memória alocada não é liberada, causando degradação" },
  { word: "Merge", pronunciation: "Mêrdj", meaning: "Unir duas branches de código em uma só no Git" },
  { word: "Method", pronunciation: "Mé-thêd", meaning: "Função definida dentro de uma classe ou objeto" },
  { word: "Microservices", pronunciation: "Mái-kro-sêr-vi-ses", meaning: "Arquitetura onde a aplicação é dividida em serviços independentes" },
  { word: "Middleware", pronunciation: "Míd-el-uér", meaning: "Software intermediário que processa requisições entre sistemas" },
  { word: "Migration", pronunciation: "Mai-gréi-shen", meaning: "Script que altera a estrutura do banco de dados de forma controlada" },
  { word: "Minification", pronunciation: "Mí-ni-fi-kéi-shen", meaning: "Reduzir o tamanho de arquivos removendo espaços e comentários" },
  { word: "Mock", pronunciation: "Mók", meaning: "Objeto simulado usado em testes para substituir dependências reais" },
  { word: "Mock API", pronunciation: "Mók Éi-Pí-Ái", meaning: "API simulada para desenvolvimento e testes sem servidor real" },
  { word: "Modal", pronunciation: "Mô-del", meaning: "Janela de diálogo que aparece sobreposta ao conteúdo principal" },
  { word: "Model", pronunciation: "Mó-del", meaning: "Representação de dados e regras de negócio em uma aplicação" },
  { word: "Module", pronunciation: "Mó-djul", meaning: "Unidade independente de código que pode ser importada e reutilizada" },
  { word: "MongoDB", pronunciation: "Món-go-Dí-Bí", meaning: "Banco de dados NoSQL que armazena dados em formato de documentos" },
  { word: "Monolith", pronunciation: "Mó-no-lith", meaning: "Aplicação desenvolvida como um único bloco unificado" },
  { word: "Monorepo", pronunciation: "Mó-no-rí-pô", meaning: "Repositório único que contém múltiplos projetos relacionados" },
  { word: "Monitoring", pronunciation: "Mó-ni-te-rin", meaning: "Acompanhamento contínuo do estado e desempenho de sistemas" },
  { word: "Mount", pronunciation: "Máunt", meaning: "Inicializar e inserir um componente na árvore do DOM" },
  { word: "Mouse", pronunciation: "Máus", meaning: "Dispositivo de entrada que controla o cursor na tela" },
  { word: "Mutation", pronunciation: "Miú-téi-shen", meaning: "Alteração direta de estado ou dados em um sistema" },
  { word: "MVC", pronunciation: "Êm-Ví-Sí", meaning: "Model-View-Controller — padrão de arquitetura de software" },
  { word: "MySQL", pronunciation: "Mái-És-Kiú-Él", meaning: "Sistema de gerenciamento de banco de dados relacional open source" },
  { word: "Namespace", pronunciation: "Néim-speis", meaning: "Espaço de nomes que organiza identificadores para evitar conflitos" },
  { word: "Native", pronunciation: "Néi-tiv", meaning: "Aplicação desenvolvida especificamente para uma plataforma" },
  { word: "Network", pronunciation: "Nét-uérk", meaning: "Conjunto de computadores e dispositivos interconectados" },
  { word: "Nesting", pronunciation: "Nés-tin", meaning: "Colocar elementos ou funções dentro de outros elementos" },
  { word: "Next.js", pronunciation: "Nékst-Djéi-És", meaning: "Framework React para produção com SSR e geração estática" },
  { word: "Node", pronunciation: "Nôd", meaning: "Nó em uma estrutura de dados ou o runtime Node.js para JavaScript" },
  { word: "NoSQL", pronunciation: "Nô-És-Kiú-Él", meaning: "Banco de dados não relacional, flexível e escalável" },
  { word: "NPM", pronunciation: "Én-Pí-Êm", meaning: "Node Package Manager — gerenciador de pacotes do Node.js" },
  { word: "Null", pronunciation: "Nâl", meaning: "Valor que representa ausência intencional de um objeto" },
  { word: "Nuxt", pronunciation: "Nâkst", meaning: "Framework Vue.js para produção com SSR e geração estática" },
  { word: "OAuth", pronunciation: "Ô-Ôth", meaning: "Protocolo padrão de autorização para acesso seguro entre serviços" },
  { word: "Object", pronunciation: "Ób-djékt", meaning: "Entidade com propriedades e métodos em programação orientada a objetos" },
  { word: "Observer Pattern", pronunciation: "Ob-sêr-ver Pé-tern", meaning: "Padrão onde objetos notificam outros sobre mudanças de estado" },
  { word: "Open Source", pronunciation: "Ô-pen Sórs", meaning: "Software com código-fonte aberto e livre para uso e modificação" },
  { word: "Operator", pronunciation: "Ó-pe-réi-ter", meaning: "Símbolo que realiza operação como +, -, &&, ||" },
  { word: "ORM", pronunciation: "Ô-Ár-Êm", meaning: "Object-Relational Mapping — mapeia objetos para tabelas do banco" },
  { word: "Output", pronunciation: "Áut-put", meaning: "Dados ou resultados produzidos por uma função ou sistema" },
  { word: "Override", pronunciation: "Ô-ver-ráid", meaning: "Sobrescrever o comportamento de um método herdado" },
  { word: "Package", pronunciation: "Pé-kidj", meaning: "Pacote de código com funcionalidades distribuído via gerenciador" },
  { word: "Pagination", pronunciation: "Péi-dji-néi-shen", meaning: "Dividir resultados grandes em páginas menores e navegáveis" },
  { word: "Parallelism", pronunciation: "Pé-re-le-li-zem", meaning: "Execução simultânea real de múltiplas tarefas em núcleos distintos" },
  { word: "Parameter", pronunciation: "Pê-ré-mi-ter", meaning: "Variável definida na assinatura de uma função para receber valores" },
  { word: "Parser", pronunciation: "Pár-ser", meaning: "Analisador que interpreta e converte dados de um formato" },
  { word: "Password", pronunciation: "Pés-uerd", meaning: "Senha secreta usada para autenticar o acesso a um sistema" },
  { word: "Patch", pronunciation: "Pétch", meaning: "Atualização pequena que corrige um bug ou vulnerabilidade" },
  { word: "Pattern", pronunciation: "Pé-tern", meaning: "Solução reutilizável para problemas recorrentes de design de software" },
  { word: "Payload", pronunciation: "Péi-lôd", meaning: "Dados enviados no corpo de uma requisição ou resposta" },
  { word: "Performance", pronunciation: "Per-fór-mens", meaning: "Medida de velocidade e eficiência de um sistema ou código" },
  { word: "PHP", pronunciation: "Pí-Éitch-Pí", meaning: "Linguagem de programação server-side amplamente usada na web" },
  { word: "Ping", pronunciation: "Pín", meaning: "Comando para testar conectividade e medir latência de rede" },
  { word: "Pipeline", pronunciation: "Páip-lain", meaning: "Sequência de etapas automatizadas para processar dados ou fazer deploy" },
  { word: "Pixel", pronunciation: "Píks-el", meaning: "Menor unidade de uma imagem digital ou tela" },
  { word: "Placeholder", pronunciation: "Pléis-hôl-der", meaning: "Texto de exemplo exibido em campos de formulário vazios" },
  { word: "Platform", pronunciation: "Plét-fórm", meaning: "Ambiente ou infraestrutura onde software é desenvolvido e executado" },
  { word: "Plugin", pronunciation: "Plâ-gin", meaning: "Extensão que adiciona funcionalidades a um software existente" },
  { word: "Polling", pronunciation: "Pô-lin", meaning: "Verificação periódica de um estado ou recurso no servidor" },
  { word: "Polymorphism", pronunciation: "Pó-li-mór-fi-zem", meaning: "Capacidade de um objeto assumir diferentes formas ou comportamentos" },
  { word: "Popup", pronunciation: "Pó-pâp", meaning: "Janela que aparece sobre o conteúdo principal da página" },
  { word: "Port", pronunciation: "Port", meaning: "Número que identifica um serviço específico em um servidor" },
  { word: "PostgreSQL", pronunciation: "Pós-grês-És-Kiú-Él", meaning: "Banco de dados relacional open source poderoso e extensível" },
  { word: "Postman", pronunciation: "Pôst-men", meaning: "Ferramenta popular para testar e documentar APIs" },
  { word: "Prettier", pronunciation: "Prí-ti-er", meaning: "Formatador automático de código que garante estilo consistente" },
  { word: "Private", pronunciation: "Prái-vit", meaning: "Modificador de acesso restrito a dentro da classe" },
  { word: "Production", pronunciation: "Pro-dâk-shen", meaning: "Ambiente ao vivo onde a aplicação está disponível para usuários" },
  { word: "Profiler", pronunciation: "Prô-fái-ler", meaning: "Ferramenta para medir desempenho e identificar gargalos no código" },
  { word: "Progressive", pronunciation: "Pro-gré-siv", meaning: "Aplicação que melhora progressivamente conforme as capacidades do dispositivo" },
  { word: "Promise", pronunciation: "Pró-mis", meaning: "Objeto que representa o resultado futuro de uma operação assíncrona" },
  { word: "Prompt", pronunciation: "Prómpt", meaning: "Texto de instrução enviado a uma IA ou entrada de terminal" },
  { word: "Protocol", pronunciation: "Pró-to-kol", meaning: "Conjunto de regras para comunicação entre sistemas" },
  { word: "Prototype", pronunciation: "Prô-to-táip", meaning: "Modelo inicial de um objeto ou produto para validação" },
  { word: "Proxy", pronunciation: "Prók-si", meaning: "Intermediário entre cliente e servidor que redireciona requisições" },
  { word: "Public", pronunciation: "Pâ-blik", meaning: "Modificador de acesso disponível de qualquer lugar" },
  { word: "Pull", pronunciation: "Púl", meaning: "Baixar atualizações de um repositório remoto para o local" },
  { word: "Pull Request", pronunciation: "Púl Ri-kuést", meaning: "Solicitação para revisar e mesclar código em um repositório" },
  { word: "Push", pronunciation: "Pûsh", meaning: "Enviar commits locais para um repositório remoto" },
  { word: "Python", pronunciation: "Pái-thon", meaning: "Linguagem de programação de alto nível com sintaxe simples e poderosa" },
  { word: "Query", pronunciation: "Kuíê-ri", meaning: "Consulta estruturada para buscar dados em um banco de dados" },
  { word: "Queue", pronunciation: "Kiú", meaning: "Estrutura de dados ou sistema de fila para processar tarefas" },
  { word: "Race Condition", pronunciation: "Réis Kon-dí-shen", meaning: "Falha quando múltiplos processos acessam dados simultaneamente" },
  { word: "RAM", pronunciation: "Rém", meaning: "Random Access Memory — memória volátil e rápida do computador" },
  { word: "React", pronunciation: "Ri-ékt", meaning: "Biblioteca JavaScript do Facebook para construir interfaces de usuário" },
  { word: "React Native", pronunciation: "Ri-ékt Néi-tiv", meaning: "Framework para criar apps mobile com React e código nativo" },
  { word: "Recursion", pronunciation: "Ri-kêr-shen", meaning: "Técnica onde uma função chama a si mesma para resolver problemas" },
  { word: "Redirect", pronunciation: "Ri-dá-rêkt", meaning: "Redirecionar automaticamente o usuário para outra URL" },
  { word: "Redis", pronunciation: "Ré-dis", meaning: "Banco de dados em memória de alta performance para cache e sessões" },
  { word: "Redux", pronunciation: "Rí-dâks", meaning: "Biblioteca para gerenciamento centralizado de estado em JavaScript" },
  { word: "Refactor", pronunciation: "Ri-fék-ter", meaning: "Reorganizar código sem alterar seu comportamento externo" },
  { word: "Regex", pronunciation: "Rí-djêks", meaning: "Expressão regular para buscar e validar padrões em texto" },
  { word: "Regression", pronunciation: "Ri-gré-shen", meaning: "Retorno de um bug que havia sido corrigido anteriormente" },
  { word: "Release", pronunciation: "Ri-lís", meaning: "Lançamento oficial de uma versão de software para usuários" },
  { word: "Remote", pronunciation: "Ri-môt", meaning: "Acesso ou repositório localizado em servidor externo" },
  { word: "Rendering", pronunciation: "Rên-de-rin", meaning: "Processo de transformar dados em interface visual na tela" },
  { word: "Repository", pronunciation: "Ri-pó-zi-tó-ri", meaning: "Local onde o código-fonte e histórico de versões são armazenados" },
  { word: "Request", pronunciation: "Ri-kuést", meaning: "Mensagem enviada pelo cliente solicitando dados ao servidor" },
  { word: "Resource", pronunciation: "Rí-sors", meaning: "Dado ou entidade acessível através de uma API" },
  { word: "Response", pronunciation: "Ri-spóns", meaning: "Resposta do servidor à requisição do cliente" },
  { word: "REST", pronunciation: "Rést", meaning: "Representational State Transfer — estilo de arquitetura para APIs web" },
  { word: "Rollback", pronunciation: "Rôl-béck", meaning: "Reverter para uma versão anterior em caso de falha" },
  { word: "Route", pronunciation: "Rút", meaning: "Caminho de URL que mapeia para uma funcionalidade da aplicação" },
  { word: "Router", pronunciation: "Rú-ter", meaning: "Componente que gerencia e direciona o fluxo de navegação" },
  { word: "Ruby", pronunciation: "Rú-bi", meaning: "Linguagem de programação focada em simplicidade e elegância" },
  { word: "Runtime", pronunciation: "Rân-táim", meaning: "Ambiente e período de execução de um programa" },
  { word: "Rust", pronunciation: "Rãst", meaning: "Linguagem de programação de sistema focada em segurança e performance" },
  { word: "Sass", pronunciation: "Séss", meaning: "Pré-processador CSS que adiciona variáveis, mixins e aninhamento" },
  { word: "Scalability", pronunciation: "Skéi-le-bí-li-ti", meaning: "Capacidade de um sistema crescer para suportar mais carga" },
  { word: "Schema", pronunciation: "Skí-me", meaning: "Estrutura formal que define a organização de dados" },
  { word: "Scope", pronunciation: "Skôp", meaning: "Contexto onde uma variável ou função é visível e acessível" },
  { word: "Script", pronunciation: "Skrípt", meaning: "Arquivo de código executável que automatiza tarefas" },
  { word: "Scroll", pronunciation: "Skrôl", meaning: "Rolagem vertical ou horizontal de uma página ou elemento" },
  { word: "SDK", pronunciation: "És-Dí-Kéi", meaning: "Kit de Desenvolvimento de Software com ferramentas e bibliotecas" },
  { word: "Security", pronunciation: "Si-kiú-ri-ti", meaning: "Conjunto de práticas para proteger sistemas e dados" },
  { word: "Semaphore", pronunciation: "Sé-me-fôr", meaning: "Mecanismo de sincronização para controlar acesso concorrente" },
  { word: "Semantic", pronunciation: "Si-mén-tik", meaning: "Código ou markup com significado estrutural e contextual claro" },
  { word: "Serialization", pronunciation: "Si-ri-e-li-zéi-shen", meaning: "Converter um objeto em formato transmissível como JSON ou XML" },
  { word: "Server", pronunciation: "Sêr-ver", meaning: "Computador ou programa que fornece serviços para outros" },
  { word: "Serverless", pronunciation: "Sêr-ver-les", meaning: "Arquitetura onde o servidor é gerenciado pelo provedor de nuvem" },
  { word: "Session", pronunciation: "Sé-shen", meaning: "Período de interação autenticada entre usuário e sistema" },
  { word: "Setter", pronunciation: "Sé-ter", meaning: "Método que define ou altera o valor de uma propriedade" },
  { word: "Sharding", pronunciation: "Shár-din", meaning: "Dividir banco de dados em partes menores para escalabilidade" },
  { word: "Sidebar", pronunciation: "Sáid-bár", meaning: "Barra lateral de navegação ou conteúdo em uma interface" },
  { word: "Singleton", pronunciation: "Sín-gel-ten", meaning: "Padrão que garante que apenas uma instância de uma classe exista" },
  { word: "Slug", pronunciation: "Slãg", meaning: "Versão amigável de texto para uso em URLs" },
  { word: "Snippet", pronunciation: "Sní-pet", meaning: "Fragmento pequeno e reutilizável de código" },
  { word: "Socket", pronunciation: "Só-ket", meaning: "Canal de comunicação bidirecional e persistente entre sistemas" },
  { word: "Software", pronunciation: "Sóft-uér", meaning: "Conjunto de programas e aplicações que executam tarefas no computador" },
  { word: "SQL", pronunciation: "És-Kiú-Él", meaning: "Structured Query Language — linguagem padrão para bancos relacionais" },
  { word: "SSH", pronunciation: "És-És-Éitch", meaning: "Protocolo seguro para acesso remoto a servidores" },
  { word: "SSL", pronunciation: "És-És-Él", meaning: "Protocolo de segurança que criptografa comunicações web" },
  { word: "Stack", pronunciation: "Stéck", meaning: "Conjunto de tecnologias usadas em um projeto ou estrutura de dados LIFO" },
  { word: "Staging", pronunciation: "Stéi-djin", meaning: "Ambiente de testes que replica produção antes do deploy final" },
  { word: "State", pronunciation: "Stéit", meaning: "Dados que representam a condição atual de um componente ou aplicação" },
  { word: "State Management", pronunciation: "Stéit Mé-nidj-ment", meaning: "Técnicas para controlar e compartilhar estado na aplicação" },
  { word: "Static", pronunciation: "Sté-tik", meaning: "Conteúdo fixo que não muda dinamicamente" },
  { word: "Static Site", pronunciation: "Sté-tik Sáit", meaning: "Site gerado previamente como arquivos HTML estáticos" },
  { word: "Strict Mode", pronunciation: "Strikt Môd", meaning: "Modo que aplica regras mais rígidas de execução no JavaScript" },
  { word: "String", pronunciation: "Strín", meaning: "Tipo de dado que representa sequência de caracteres de texto" },
  { word: "Stub", pronunciation: "Stâb", meaning: "Implementação mínima de uma função usada em testes" },
  { word: "Submodule", pronunciation: "Sâb-mó-djul", meaning: "Repositório Git aninhado dentro de outro repositório" },
  { word: "Swagger", pronunciation: "Suá-guer", meaning: "Especificação e ferramenta para documentar APIs REST" },
  { word: "Switch", pronunciation: "Suítch", meaning: "Estrutura de controle que testa múltiplos casos de um valor" },
  { word: "Symlink", pronunciation: "Sím-link", meaning: "Atalho simbólico que aponta para outro arquivo ou diretório" },
  { word: "Syntax", pronunciation: "Sín-téks", meaning: "Conjunto de regras gramaticais de uma linguagem de programação" },
  { word: "Syntax Highlighting", pronunciation: "Sín-téks Hái-lai-tin", meaning: "Coloração do código-fonte para melhorar leitura e identificação" },
  { word: "TDD", pronunciation: "Tí-Dí-Dí", meaning: "Test-Driven Development — escrever testes antes do código" },
  { word: "Template", pronunciation: "Têm-plêt", meaning: "Modelo reutilizável com estrutura predefinida para gerar conteúdo" },
  { word: "Terminal", pronunciation: "Têr-mi-nel", meaning: "Interface de linha de comando para interagir com o sistema" },
  { word: "Terraform", pronunciation: "Té-re-fórm", meaning: "Ferramenta para definir e provisionar infraestrutura como código" },
  { word: "Testing", pronunciation: "Tés-tin", meaning: "Processo de verificar se o software funciona corretamente" },
  { word: "Thread", pronunciation: "Thrêd", meaning: "Unidade de execução dentro de um processo, podendo ser paralela" },
  { word: "Timeout", pronunciation: "Táim-áut", meaning: "Tempo limite após o qual uma operação é cancelada" },
  { word: "Token", pronunciation: "Tô-ken", meaning: "Chave ou identificador único usado para autenticação" },
  { word: "Tooling", pronunciation: "Tú-lin", meaning: "Conjunto de ferramentas que auxiliam o processo de desenvolvimento" },
  { word: "Transpiler", pronunciation: "Trêns-pái-ler", meaning: "Compilador que converte código de uma linguagem para outra similar" },
  { word: "Tree", pronunciation: "Trí", meaning: "Estrutura de dados hierárquica com nós e ramificações" },
  { word: "Trigger", pronunciation: "Trí-guer", meaning: "Evento ou condição que dispara automaticamente uma ação" },
  { word: "TypeScript", pronunciation: "Táip-Skrípt", meaning: "Superset do JavaScript que adiciona tipagem estática" },
  { word: "UI", pronunciation: "iú-Ái", meaning: "User Interface — interface visual com que o usuário interage" },
  { word: "Undefined", pronunciation: "Ân-di-fáind", meaning: "Valor de variável declarada mas ainda não inicializada" },
  { word: "Unit Test", pronunciation: "iú-nit Tést", meaning: "Teste que verifica uma unidade isolada de código" },
  { word: "Unix", pronunciation: "iú-niks", meaning: "Sistema operacional que serviu de base para Linux e macOS" },
  { word: "Upload", pronunciation: "Ãp-lôd", meaning: "Transferir arquivo do dispositivo local para um servidor" },
  { word: "URL", pronunciation: "iú-Ár-Él", meaning: "Uniform Resource Locator — endereço único de um recurso na web" },
  { word: "User", pronunciation: "iú-zer", meaning: "Pessoa que utiliza um sistema, aplicação ou serviço" },
  { word: "UUID", pronunciation: "iú-iú-Ái-Dí", meaning: "Universally Unique Identifier — identificador único gerado aleatoriamente" },
  { word: "UX", pronunciation: "iú-Éks", meaning: "User Experience — experiência e satisfação do usuário ao usar o produto" },
  { word: "Validation", pronunciation: "Vé-li-déi-shen", meaning: "Verificação se dados de entrada atendem a critérios definidos" },
  { word: "Variable", pronunciation: "Vé-ri-ê-bel", meaning: "Espaço de memória nomeado que armazena um valor" },
  { word: "Vector", pronunciation: "Vék-ter", meaning: "Estrutura de dados dinâmica ou imagem de gráfico escalável" },
  { word: "Version", pronunciation: "Vêr-shen", meaning: "Identificador de um estado específico do software ao longo do tempo" },
  { word: "Versioning", pronunciation: "Vêr-she-nin", meaning: "Sistema para controlar e identificar versões de software" },
  { word: "View", pronunciation: "Viú", meaning: "Camada responsável pela apresentação visual de dados" },
  { word: "Virtual", pronunciation: "Vêr-tchel", meaning: "Emulado por software, não existindo fisicamente" },
  { word: "Virtual DOM", pronunciation: "Vêr-tchel Dóm", meaning: "Representação em memória do DOM para otimizar atualizações" },
  { word: "Vue", pronunciation: "Viú", meaning: "Framework JavaScript progressivo para criar interfaces de usuário" },
  { word: "Vulnerability", pronunciation: "Vâl-ne-re-bí-li-ti", meaning: "Falha de segurança que pode ser explorada por atacantes" },
  { word: "Web Assembly", pronunciation: "Uéb Ê-sêm-bli", meaning: "Formato binário que permite código de alta performance no browser" },
  { word: "WebGL", pronunciation: "Uéb-Djí-Él", meaning: "API JavaScript para renderizar gráficos 3D no navegador" },
  { word: "Webhook", pronunciation: "Uéb-húk", meaning: "Notificação HTTP automática enviada quando um evento ocorre" },
  { word: "WebSocket", pronunciation: "Uéb-Só-ket", meaning: "Protocolo de comunicação bidirecional e persistente via web" },
  { word: "Webpack", pronunciation: "Uéb-péck", meaning: "Empacotador de módulos JavaScript para otimizar assets" },
  { word: "Widget", pronunciation: "Uí-djêt", meaning: "Componente visual interativo reutilizável de interface" },
  { word: "Whitespace", pronunciation: "Uáit-speis", meaning: "Espaços em branco, tabs e quebras de linha no código" },
  { word: "Workflow", pronunciation: "Uérk-flô", meaning: "Sequência de etapas automatizadas para completar um processo" },
  { word: "Wrapper", pronunciation: "Ré-per", meaning: "Camada que envolve uma função ou componente adicionando comportamento" },
  { word: "XML", pronunciation: "Êks-Êm-Él", meaning: "Extensible Markup Language — formato de dados legível por máquinas" },
  { word: "XSS", pronunciation: "Êks-És-És", meaning: "Cross-Site Scripting — ataque que injeta código malicioso em páginas" },
  { word: "YAML", pronunciation: "Iém-êl", meaning: "Formato legível de serialização de dados usado em configurações" },
  { word: "Yarn", pronunciation: "Iárn", meaning: "Gerenciador de pacotes JavaScript alternativo ao NPM" },
  { word: "Zero Config", pronunciation: "Zí-ro Kon-fíg", meaning: "Ferramenta que funciona sem necessidade de configuração manual" },
  { word: "Zero-Day", pronunciation: "Zí-ro-Dei", meaning: "Vulnerabilidade recém-descoberta sem patch disponível ainda" },
  { word: "SSR", pronunciation: "És-És-Ár", meaning: "Server-Side Rendering — renderização da página no servidor antes de enviar ao navegador" },
  { word: "CSR", pronunciation: "Sí-És-Ár", meaning: "Client-Side Rendering — renderização feita diretamente no navegador do usuário" },
  { word: "SPA", pronunciation: "És-Pí-Êi", meaning: "Single Page Application — aplicação web carregada em uma única página" },
  { word: "MPA", pronunciation: "Êm-Pí-Êi", meaning: "Multi Page Application — aplicação composta por múltiplas páginas separadas" },
  { word: "Hydrate", pronunciation: "Hái-drêit", meaning: "Ativar interatividade JavaScript em HTML renderizado previamente" },
  { word: "Re-render", pronunciation: "Ri-Rên-der", meaning: "Renderizar novamente um componente após mudança de estado" },
  { word: "Props", pronunciation: "Próps", meaning: "Dados passados de um componente pai para um componente filho no React" },
  { word: "State Hook", pronunciation: "Stéit Húk", meaning: "Hook usado para controlar estado dentro de componentes React" },
  { word: "Effect Hook", pronunciation: "I-fékt Húk", meaning: "Hook utilizado para executar efeitos colaterais em componentes React" },
  { word: "Context API", pronunciation: "Kón-tekst Éi-Pí-Ái", meaning: "Sistema nativo do React para compartilhar estado global" },
  { word: "Memoization", pronunciation: "Mé-mo-i-zéi-shen", meaning: "Otimização que evita cálculos repetidos reutilizando resultados" },
  { word: "Virtualization", pronunciation: "Vêr-tchu-a-lai-zéi-shen", meaning: "Renderização parcial de listas grandes para melhorar performance" },
  { word: "Skeleton Loader", pronunciation: "Ské-le-ten Lô-der", meaning: "Placeholder visual exibido enquanto conteúdo está carregando" },
  { word: "Infinite Scroll", pronunciation: "Ín-fi-nit Skrôl", meaning: "Carregamento contínuo de conteúdo durante a rolagem da página" },
  { word: "Responsive Design", pronunciation: "Ri-spón-siv Di-záin", meaning: "Design adaptável a diferentes tamanhos de tela e dispositivos" },
  { word: "Media Query", pronunciation: "Mí-dia Kuíê-ri", meaning: "Regra CSS usada para aplicar estilos conforme resolução da tela" },
  { word: "Tailwind CSS", pronunciation: "Téil-uind Sí-És-És", meaning: "Framework utility-first para estilização rápida de interfaces" },
  { word: "Styled Components", pronunciation: "Stái-ld Kom-pô-nents", meaning: "Biblioteca para escrever CSS dentro de componentes JavaScript" },
  { word: "PWA", pronunciation: "Pí-Dâb-iú-Êi", meaning: "Progressive Web App — aplicação web com experiência similar a app nativo" },
  { word: "Web Vitals", pronunciation: "Uéb Vái-tels", meaning: "Métricas usadas para medir experiência e performance de páginas web" },
  { word: "Tree Shaking", pronunciation: "Trí Shêi-kin", meaning: "Remoção automática de código não utilizado no bundle final" },
  { word: "Code Splitting", pronunciation: "Kôd Splí-tin", meaning: "Divisão do código em partes menores carregadas sob demanda" },
  { word: "Hydration Error", pronunciation: "Hai-drêi-shen É-ror", meaning: "Erro causado por diferença entre HTML do servidor e cliente" },
  { word: "BFF", pronunciation: "Bí-Éf-Éf", meaning: "Backend For Frontend — camada backend específica para um frontend" },
  { word: "Rate Limit", pronunciation: "Rêit Lí-mit", meaning: "Limitação da quantidade de requisições permitidas em determinado período" },
  { word: "Throttling", pronunciation: "Thró-tlin", meaning: "Controle que reduz frequência de execução de eventos ou requisições" },
  { word: "Reverse Proxy", pronunciation: "Ri-vêrs Prók-si", meaning: "Servidor intermediário que recebe requisições antes do backend principal" },
  { word: "Nginx", pronunciation: "Ên-djin-Éks", meaning: "Servidor web e reverse proxy de alta performance" },
  { word: "Web Server", pronunciation: "Uéb Sêr-ver", meaning: "Servidor responsável por entregar páginas e arquivos web" },
  { word: "Application Server", pronunciation: "É-pli-kêi-shen Sêr-ver", meaning: "Servidor responsável pela execução da lógica da aplicação" },
  { word: "ORM Migration", pronunciation: "Ô-Ár-Êm Mai-gréi-shen", meaning: "Alteração controlada da estrutura do banco usando ORM" },
  { word: "Seed", pronunciation: "Síd", meaning: "Dados iniciais inseridos automaticamente no banco de dados" },
  { word: "Seeder", pronunciation: "Sí-der", meaning: "Script responsável por popular banco de dados com dados iniciais" },
  { word: "Connection Pool", pronunciation: "Ko-nék-shen Púl", meaning: "Conjunto reutilizável de conexões abertas com banco de dados" },
  { word: "Transaction", pronunciation: "Trên-zék-shen", meaning: "Grupo de operações executadas de forma segura e atômica no banco" },
  { word: "Replica Set", pronunciation: "Ré-pli-ka Sét", meaning: "Conjunto de réplicas sincronizadas de banco de dados para redundância" },
  { word: "Failover", pronunciation: "Fêil-ô-ver", meaning: "Troca automática para sistema secundário em caso de falha" },
  { word: "Horizontal Scaling", pronunciation: "Hó-ri-zón-tel Skéi-lin", meaning: "Escalar adicionando mais servidores ao sistema" },
  { word: "Vertical Scaling", pronunciation: "Vêr-ti-kel Skéi-lin", meaning: "Escalar aumentando recursos de um único servidor" },
  { word: "Message Broker", pronunciation: "Mé-sidj Brô-ker", meaning: "Sistema intermediário que distribui mensagens entre serviços" },
  { word: "RabbitMQ", pronunciation: "Rá-bit Êm-Kiú", meaning: "Message broker popular baseado em filas de mensagens" },
  { word: "Kafka", pronunciation: "Kéf-ka", meaning: "Plataforma distribuída para streaming e processamento de eventos" },
  { word: "Worker", pronunciation: "Uêr-ker", meaning: "Processo responsável por executar tarefas em segundo plano" },
  { word: "Job Queue", pronunciation: "Djób Kiú", meaning: "Fila de tarefas assíncronas processadas posteriormente" },
  { word: "Cron Job", pronunciation: "Krón Djób", meaning: "Tarefa agendada para execução automática em horários específicos" },
  { word: "Observability", pronunciation: "Ob-zêr-va-bí-li-ti", meaning: "Capacidade de monitorar e entender comportamento interno de sistemas" },
  { word: "Tracing", pronunciation: "Trêi-sin", meaning: "Rastreamento do fluxo de uma requisição entre múltiplos serviços" },
  { word: "Health Check", pronunciation: "Hélth Chék", meaning: "Verificação automática do estado e disponibilidade de um serviço" },
  { word: "API Gateway", pronunciation: "Éi-Pí-Ái Guéit-uéi", meaning: "Camada central que gerencia autenticação, rotas e tráfego de APIs" },
  { word: "Service Discovery", pronunciation: "Sêr-vis Dis-kâ-ve-ri", meaning: "Mecanismo que permite serviços encontrarem outros dinamicamente" },
  { word: "Circuit Retry", pronunciation: "Sêr-kit Ri-trái", meaning: "Tentativa automática de repetir chamadas que falharam" },
  { word: "Blue-Green Deploy", pronunciation: "Blú-Grín Di-plói", meaning: "Estratégia de deploy com dois ambientes para evitar downtime" },
  { word: "Canary Release", pronunciation: "Ke-né-ri Ri-lís", meaning: "Liberação gradual de nova versão para pequena parte dos usuários" },
  { word: "Feature Branch", pronunciation: "Fí-cher Brénch", meaning: "Branch criada especificamente para desenvolvimento de uma funcionalidade" },
  { word: "Monorepo Tooling", pronunciation: "Mó-no-rí-pô Tú-lin", meaning: "Ferramentas para gerenciamento de múltiplos projetos em monorepo" },
  { word: "Nx", pronunciation: "Én-Éks", meaning: "Ferramenta para gerenciamento avançado de monorepos JavaScript" },
  { word: "Turborepo", pronunciation: "Têr-bo-rí-pô", meaning: "Sistema de build otimizado para monorepos JavaScript e TypeScript" },
  { word: "Bun", pronunciation: "Bân", meaning: "Runtime JavaScript moderno focado em velocidade e simplicidade" },
  { word: "Vite", pronunciation: "Vít", meaning: "Ferramenta de build frontend extremamente rápida para projetos modernos" },
  { word: "Prisma", pronunciation: "Príz-me", meaning: "ORM moderno para TypeScript e Node.js com tipagem automática" },
  { word: "tRPC", pronunciation: "Tí-Ár-Pí-Sí", meaning: "Framework para APIs typesafe entre frontend e backend com TypeScript" },
  { word: "Zod", pronunciation: "Zód", meaning: "Biblioteca TypeScript para validação e tipagem de dados" },
  { word: "Server Actions", pronunciation: "Sêr-ver Ék-shens", meaning: "Funções executadas diretamente no servidor em frameworks modernos" },
  { word: "Edge Runtime", pronunciation: "Édj Rân-táim", meaning: "Execução de código próximo do usuário em servidores distribuídos" },
  { word: "Edge Function", pronunciation: "Édj Fânk-shen", meaning: "Função serverless executada em edge locations ao redor do mundo" },
  { word: "ISR", pronunciation: "Ái-És-Ár", meaning: "Incremental Static Regeneration — regeneração incremental de páginas estáticas" },
  { word: "Server Component", pronunciation: "Sêr-ver Kom-pô-nent", meaning: "Componente React renderizado exclusivamente no servidor" },
  { word: "Client Component", pronunciation: "Klái-ent Kom-pô-nent", meaning: "Componente React executado diretamente no navegador do usuário" },
  { word: "Streaming", pronunciation: "Strí-min", meaning: "Envio contínuo de dados ou conteúdo conforme fica disponível" },
  { word: "Suspense", pronunciation: "Sâs-pens", meaning: "Recurso do React para lidar com carregamento assíncrono de componentes" },
  { word: "Hydration Boundary", pronunciation: "Hai-drêi-shen Báun-de-ri", meaning: "Limite onde ocorre hidratação parcial em aplicações React modernas" },
  { word: "DOM Manipulation", pronunciation: "Dóm Me-ni-piu-léi-shen", meaning: "Alteração dinâmica de elementos HTML via JavaScript" },
  { word: "Query Selector", pronunciation: "Kuíê-ri Se-lék-ter", meaning: "Método JavaScript usado para selecionar elementos do DOM" },
  { word: "addEventListener", pronunciation: "Éd I-vênt Lí-ste-ner", meaning: "Método JavaScript para registrar eventos em elementos" },
  { word: "ClassList", pronunciation: "Kléss Líst", meaning: "API usada para adicionar, remover ou alternar classes CSS" },
  { word: "InnerHTML", pronunciation: "Í-ner Éich-Tí-Êm-Él", meaning: "Propriedade usada para ler ou alterar HTML interno de um elemento" },
  { word: "TextContent", pronunciation: "Tékst Kón-tent", meaning: "Propriedade usada para acessar ou definir texto puro em elementos" },
  { word: "Local Scope", pronunciation: "Lô-kel Skôp", meaning: "Escopo acessível apenas dentro de uma função ou bloco" },
  { word: "Global Scope", pronunciation: "Glô-bel Skôp", meaning: "Escopo acessível em qualquer parte do código" },
  { word: "Hoisting", pronunciation: "Róis-tin", meaning: "Comportamento onde declarações são movidas para o topo do escopo" },
  { word: "Truthy", pronunciation: "Trú-thi", meaning: "Valor interpretado como verdadeiro em condições JavaScript" },
  { word: "Falsy", pronunciation: "Fól-si", meaning: "Valor interpretado como falso em condições JavaScript" },
  { word: "Template Literal", pronunciation: "Têm-pleit Lí-te-rel", meaning: "Sintaxe moderna para interpolação de strings usando crases" },
  { word: "Spread Operator", pronunciation: "Spréd Ó-pe-rêi-ter", meaning: "Operador (...) usado para expandir arrays ou objetos" },
  { word: "Rest Operator", pronunciation: "Rést Ó-pe-rêi-ter", meaning: "Operador usado para agrupar múltiplos valores em array" },
  { word: "Arrow Function", pronunciation: "É-ro Fânk-shen", meaning: "Sintaxe curta para criar funções em JavaScript" },
  { word: "Anonymous Function", pronunciation: "Ê-nó-ni-mes Fânk-shen", meaning: "Função criada sem nome definido" },
  { word: "Event Bubbling", pronunciation: "I-vênt Bâ-belin", meaning: "Propagação de eventos do elemento filho para o pai" },
  { word: "Event Delegation", pronunciation: "I-vênt Dé-le-guei-shen", meaning: "Técnica de capturar eventos em elementos pais para otimização" },
  { word: "Prevent Default", pronunciation: "Pri-vênt Di-fólt", meaning: "Método usado para impedir comportamento padrão de um evento" },
  { word: "Stop Propagation", pronunciation: "Stóp Pró-pe-guei-shen", meaning: "Método que impede propagação de eventos no DOM" },
  { word: "DOMContentLoaded", pronunciation: "Dóm Kón-tent Lô-ded", meaning: "Evento disparado quando HTML termina de carregar" },
  { word: "Viewport", pronunciation: "Viú-port", meaning: "Área visível da página no navegador do usuário" },
  { word: "Flexbox", pronunciation: "Fléks-bóks", meaning: "Sistema CSS para alinhamento e distribuição de elementos flexíveis" },
  { word: "CSS Grid", pronunciation: "Sí-És-És Gríd", meaning: "Sistema CSS bidimensional para layouts complexos" },
  { word: "Position Absolute", pronunciation: "Po-zí-shen Éb-so-lút", meaning: "Posicionamento CSS relativo ao ancestral posicionado" },
  { word: "Position Relative", pronunciation: "Po-zí-shen Ré-le-tiv", meaning: "Posicionamento CSS relativo à posição original do elemento" },
  { word: "Position Fixed", pronunciation: "Po-zí-shen Fíkst", meaning: "Posicionamento fixo em relação à janela do navegador" },
  { word: "Z-Index", pronunciation: "Zí-Ín-deks", meaning: "Controle de sobreposição de elementos no CSS" },
  { word: "Overflow", pronunciation: "Ô-ver-flô", meaning: "Controle de conteúdo excedente dentro de um elemento" },
  { word: "Opacity", pronunciation: "Ô-pé-si-ti", meaning: "Nível de transparência visual de um elemento" },
  { word: "Hover", pronunciation: "Ró-ver", meaning: "Estado ativado quando cursor passa sobre um elemento" },
  { word: "Transition", pronunciation: "Trên-zí-shen", meaning: "Animação suave entre mudanças de propriedades CSS" },
  { word: "Transform", pronunciation: "Trêns-fórm", meaning: "Propriedade CSS para rotacionar, mover ou escalar elementos" },
  { word: "Keyframe", pronunciation: "Kéi-frêim", meaning: "Definição de etapas de uma animação CSS" },
  { word: "Pseudo-class", pronunciation: "Sú-do Kléss", meaning: "Classe CSS aplicada em estados especiais de elementos" },
  { word: "Pseudo-element", pronunciation: "Sú-do É-le-ment", meaning: "Elemento virtual criado via CSS como ::before e ::after" },
  { word: "Box Model", pronunciation: "Bóks Mó-del", meaning: "Modelo CSS composto por margin, border, padding e content" },
  { word: "Box Shadow", pronunciation: "Bóks Shé-dô", meaning: "Sombra aplicada visualmente em elementos HTML" },
  { word: "Border Radius", pronunciation: "Bór-der Rêi-di-es", meaning: "Arredondamento dos cantos de elementos no CSS" },
  { word: "Media Element", pronunciation: "Mí-dia É-le-ment", meaning: "Elemento HTML usado para áudio ou vídeo" },
  { word: "Semantic HTML", pronunciation: "Si-mén-tik Éich-Tí-Êm-Él", meaning: "Uso de tags HTML com significado estrutural apropriado" },
  { word: "Anchor Tag", pronunciation: "Én-kor Tég", meaning: "Tag HTML usada para criar links clicáveis" },
  { word: "Form Validation", pronunciation: "Fórm Vé-li-dêi-shen", meaning: "Verificação de dados inseridos em formulários HTML" },
  { word: "Input Field", pronunciation: "Ín-put Fíld", meaning: "Campo HTML usado para entrada de dados do usuário" },
  { word: "Checkbox", pronunciation: "Chék-bóks", meaning: "Campo de seleção múltipla em formulários HTML" },
  { word: "Radio Button", pronunciation: "Rêi-di-ô Bâ-ten", meaning: "Campo HTML usado para seleção única entre opções" },
  { word: "Submit", pronunciation: "Sâb-mít", meaning: "Envio de formulário HTML para processamento" },
  { word: "Required Attribute", pronunciation: "Ri-kuái-erd É-tri-biút", meaning: "Atributo HTML que torna preenchimento obrigatório" },
  { word: "Placeholder Text", pronunciation: "Pléis-rôl-der Tékst", meaning: "Texto exibido temporariamente em campos vazios" },
  { word: "Dataset", pronunciation: "Dêi-te-sét", meaning: "API para armazenar dados customizados em elementos HTML" },
  { word: "Data Attribute", pronunciation: "Dêi-te É-tri-biút", meaning: "Atributo HTML personalizado iniciado com data-" },
  { word: "Toggle", pronunciation: "Tó-gel", meaning: "Alternar entre dois estados visuais ou funcionais" },
  { word: "Scroll Event", pronunciation: "Skrôl I-vênt", meaning: "Evento disparado durante rolagem da página" },
  { word: "Resize Event", pronunciation: "Ri-záiz I-vênt", meaning: "Evento disparado quando janela muda de tamanho" },
  { word: "Clipboard", pronunciation: "Klíp-bórd", meaning: "Área temporária usada para copiar e colar dados" },
  { word: "Dark Mode", pronunciation: "Dárk Môd", meaning: "Tema visual com cores escuras para interfaces" },
  { word: "Light Mode", pronunciation: "Láit Môd", meaning: "Tema visual com cores claras para interfaces" },
  { word: "Sticky Header", pronunciation: "Stí-ki Hé-der", meaning: "Cabeçalho fixado no topo durante scroll da página" },
  { word: "Hamburger Menu", pronunciation: "Hém-bêr-guer Mé-niu", meaning: "Ícone de menu responsivo com três linhas horizontais" },
  { word: "Lazy Image", pronunciation: "Léi-zi Í-midj", meaning: "Imagem carregada apenas quando próxima da visualização" },
  { word: "Debbuger", pronunciation: "Di-bã-ger", meaning: "Ferramenta usada para inspecionar execução e variáveis do código" },
  { word: "Console Log", pronunciation: "Kón-sôl Lóg", meaning: "Comando usado para imprimir informações no console do navegador" },
  { word: "Breakpoint Debugging", pronunciation: "Bréik-point Di-bã-guin", meaning: "Técnica de pausar execução do código em pontos específicos" },
  { word: "Source Map", pronunciation: "Sórs Méip", meaning: "Arquivo que relaciona código compilado ao código original" },
  { word: "Minified File", pronunciation: "Mí-ni-faíd Fáil", meaning: "Arquivo compactado removendo espaços e comentários" },
  { word: "Vanilla JavaScript", pronunciation: "Ve-ní-la Djá-va-skrípt", meaning: "JavaScript puro sem uso de frameworks ou bibliotecas" },
  { word: "HTML Tag", pronunciation: "Éich-Tí-Êm-Él Tég", meaning: "Elemento básico usado para estruturar conteúdo em HTML" },
  { word: "Div", pronunciation: "Dív", meaning: "Elemento HTML genérico usado para agrupar conteúdo" },
  { word: "Span", pronunciation: "Spén", meaning: "Elemento HTML inline usado para estilizar pequenos trechos" },
  { word: "Button", pronunciation: "Bâ-ten", meaning: "Elemento HTML clicável usado para ações do usuário" },
  { word: "Form", pronunciation: "Fórm", meaning: "Estrutura HTML usada para entrada e envio de dados" },
  { word: "Label", pronunciation: "Lêi-bel", meaning: "Texto associado a campos de formulário HTML" },
  { word: "Textarea", pronunciation: "Tékst-É-ri-a", meaning: "Campo HTML multilinha para textos maiores" },
  { word: "Select", pronunciation: "Si-lékt", meaning: "Campo HTML com opções selecionáveis em lista" },
  { word: "Option", pronunciation: "Óp-shen", meaning: "Item individual dentro de um elemento select" },
  { word: "Anchor", pronunciation: "Én-kor", meaning: "Elemento HTML usado para criar hyperlinks" },
  { word: "Href", pronunciation: "Éich-réf", meaning: "Atributo HTML que define destino de um link" },
  { word: "Image Tag", pronunciation: "Í-midj Tég", meaning: "Elemento HTML usado para exibir imagens" },
  { word: "Source", pronunciation: "Sórs", meaning: "Origem de arquivos como imagens, vídeos ou scripts" },
  { word: "Script Tag", pronunciation: "Skrípt Tég", meaning: "Elemento HTML usado para adicionar JavaScript" },
  { word: "Style Tag", pronunciation: "Stáil Tég", meaning: "Elemento HTML usado para inserir CSS interno" },
  { word: "Meta Tag", pronunciation: "Mé-te Tég", meaning: "Tag HTML usada para informações extras da página" },
  { word: "Title Tag", pronunciation: "Tái-tel Tég", meaning: "Tag HTML que define título exibido na aba do navegador" },
  { word: "CSS Selector", pronunciation: "Sí-És-És Si-lék-ter", meaning: "Padrão usado para selecionar elementos HTML no CSS" },
  { word: "Class Selector", pronunciation: "Kléss Si-lék-ter", meaning: "Seletor CSS baseado em classes HTML" },
  { word: "ID Selector", pronunciation: "Ái-Dí Si-lék-ter", meaning: "Seletor CSS baseado em identificador único" },
  { word: "Margin", pronunciation: "Már-djin", meaning: "Espaçamento externo de um elemento no CSS" },
  { word: "Padding", pronunciation: "Pé-din", meaning: "Espaçamento interno entre conteúdo e borda no CSS" },
  { word: "Border", pronunciation: "Bór-der", meaning: "Linha que contorna um elemento HTML" },
  { word: "Display", pronunciation: "Dis-plêi", meaning: "Propriedade CSS que define comportamento visual do elemento" },
  { word: "Inline Block", pronunciation: "Ín-láin Blók", meaning: "Elemento que combina características inline e block" },
  { word: "Block Element", pronunciation: "Blók É-le-ment", meaning: "Elemento HTML que ocupa largura inteira disponível" },
  { word: "Inline Element", pronunciation: "Ín-láin É-le-ment", meaning: "Elemento HTML exibido na mesma linha do conteúdo" },
  { word: "Font Size", pronunciation: "Fónt Sáiz", meaning: "Tamanho da fonte aplicada ao texto" },
  { word: "Font Family", pronunciation: "Fónt Fé-mi-li", meaning: "Família tipográfica usada em textos" },
  { word: "Font Weight", pronunciation: "Fónt Uêit", meaning: "Espessura visual da fonte como bold ou normal" },
  { word: "Background Color", pronunciation: "Bék-ground Kâ-ler", meaning: "Cor de fundo de um elemento HTML" },
  { word: "Text Align", pronunciation: "Tékst É-láin", meaning: "Alinhamento horizontal de texto no CSS" },
  { word: "Cursor Pointer", pronunciation: "Kêr-ser Póin-ter", meaning: "Cursor exibido indicando elemento clicável" },
  { word: "Visibility", pronunciation: "Vi-zi-bí-li-ti", meaning: "Controle CSS para exibir ou ocultar elementos" },
  { word: "Hidden", pronunciation: "Rí-den", meaning: "Elemento oculto visualmente na interface" },
  { word: "JavaScript File", pronunciation: "Djá-va-skrípt Fáil", meaning: "Arquivo contendo código JavaScript executável" },
  { word: "Const", pronunciation: "Kónst", meaning: "Declaração JavaScript para valores constantes" },
  { word: "Let", pronunciation: "Lét", meaning: "Declaração moderna JavaScript para variáveis mutáveis" },
  { word: "If Statement", pronunciation: "Íf Stêit-ment", meaning: "Estrutura condicional usada para decisões no código" },
  { word: "Else", pronunciation: "Éls", meaning: "Bloco executado quando condição do if é falsa" },
  { word: "Else If", pronunciation: "Éls Íf", meaning: "Condição adicional em estruturas condicionais JavaScript" },
  { word: "For Loop", pronunciation: "Fór Lúp", meaning: "Estrutura de repetição baseada em contador" },
  { word: "While Loop", pronunciation: "Uáil Lúp", meaning: "Loop executado enquanto condição for verdadeira" },
  { word: "Array Length", pronunciation: "Ê-rréi Lêngth", meaning: "Quantidade de elementos dentro de um array" },
  { word: "Push Method", pronunciation: "Pûsh Mé-thêd", meaning: "Método JavaScript para adicionar item em array" },
  { word: "Pop Method", pronunciation: "Póp Mé-thêd", meaning: "Método JavaScript para remover último item do array" },
  { word: "Condition", pronunciation: "Kon-dí-shen", meaning: "Expressão lógica usada em decisões do código" },
  { word: "True", pronunciation: "Trú", meaning: "Valor booleano verdadeiro no JavaScript" },
  { word: "False", pronunciation: "Fóls", meaning: "Valor booleano falso no JavaScript" },
  { word: "NaN", pronunciation: "Nót Ê Nâm-ber", meaning: "Valor que representa resultado inválido numérico" },
  { word: "Parse Int", pronunciation: "Párs Ínt", meaning: "Função usada para converter texto em número inteiro" },
  { word: "Parse Float", pronunciation: "Párs Flôt", meaning: "Função usada para converter texto em número decimal" },
  { word: "JSON Parse", pronunciation: "Djéi-Son Párs", meaning: "Converter string JSON em objeto JavaScript" },
  { word: "JSON Stringify", pronunciation: "Djéi-Son Strín-ga-fái", meaning: "Converter objeto JavaScript em texto JSON" },
  { word: "Fetch API", pronunciation: "Fétch Éi-Pí-Ái", meaning: "API moderna para realizar requisições HTTP" },
  { word: "AJAX Request", pronunciation: "Éi-djéks Ri-kuést", meaning: "Requisição assíncrona sem recarregar a página" },
  { word: "XMLHttpRequest", pronunciation: "Êks-Êm-Él-Éitch-Tí-Tí-Pí Ri-kuést", meaning: "Objeto JavaScript clássico usado em AJAX" },
  { word: "GET Request", pronunciation: "Guét Ri-kuést", meaning: "Requisição usada para buscar dados do servidor" },
  { word: "POST Request", pronunciation: "Pôust Ri-kuést", meaning: "Requisição usada para enviar dados ao servidor" },
  { word: "Status Code", pronunciation: "Sté-tes Kôd", meaning: "Código HTTP indicando resultado de uma requisição" },
  { word: "404 Error", pronunciation: "Fór Zí-ro Fór É-ror", meaning: "Erro indicando recurso não encontrado no servidor" },
  { word: "500 Error", pronunciation: "Fáiv Rân-dred É-ror", meaning: "Erro interno ocorrido no servidor" },
  { word: "CORS", pronunciation: "Kórs", meaning: "Política de segurança para requisições entre domínios diferentes" },
  { word: "Async Function", pronunciation: "Éi-sink Fânk-shen", meaning: "Função JavaScript que trabalha com operações assíncronas" },
  { word: "Await", pronunciation: "Ê-uéit", meaning: "Pausa execução até promessa assíncrona ser resolvida" },
  { word: "Promise Resolve", pronunciation: "Pró-mis Ri-zólv", meaning: "Resultado bem-sucedido de uma Promise" },
  { word: "Promise Reject", pronunciation: "Pró-mis Ri-djékt", meaning: "Falha ou erro retornado por uma Promise" },
  { word: "HTML5", pronunciation: "Éich-Tí-Êm-Él Fáiv", meaning: "Versão moderna do HTML com recursos multimídia e APIs nativas" },
  { word: "DOCTYPE", pronunciation: "Dók-táip", meaning: "Declaração que informa ao navegador a versão do HTML usada" },
  { word: "Head", pronunciation: "Réd", meaning: "Seção HTML com metadados, links e configurações da página" },
  { word: "Body", pronunciation: "Bá-di", meaning: "Seção HTML que contém conteúdo visível da página" },
  { word: "Main", pronunciation: "Mêin", meaning: "Elemento semântico que representa conteúdo principal da página" },
  { word: "Footer", pronunciation: "Fú-ter", meaning: "Rodapé semântico de página ou seção" },
  { word: "Section", pronunciation: "Sék-shen", meaning: "Agrupamento semântico de conteúdo relacionado" },
  { word: "Article", pronunciation: "Ár-ti-kel", meaning: "Conteúdo independente como post, notícia ou artigo" },
  { word: "Nav", pronunciation: "Név", meaning: "Elemento HTML usado para navegação e menus" },
  { word: "Aside", pronunciation: "Ê-sáid", meaning: "Conteúdo lateral ou complementar ao principal" },
  { word: "Paragraph", pronunciation: "Pé-re-gréf", meaning: "Elemento HTML usado para blocos de texto" },
  { word: "Heading", pronunciation: "Ré-din", meaning: "Títulos HTML representados por h1 até h6" },
  { word: "List", pronunciation: "Líst", meaning: "Estrutura HTML usada para itens organizados" },
  { word: "Ordered List", pronunciation: "Ór-derd Líst", meaning: "Lista numerada criada com a tag ol" },
  { word: "Unordered List", pronunciation: "Ân-Ór-derd Líst", meaning: "Lista sem ordem numérica criada com ul" },
  { word: "List Item", pronunciation: "Líst Ái-tem", meaning: "Item individual dentro de uma lista HTML" },
  { word: "Table", pronunciation: "Têi-bel", meaning: "Estrutura HTML usada para exibir dados em linhas e colunas" },
  { word: "Table Row", pronunciation: "Têi-bel Rôu", meaning: "Linha de uma tabela HTML" },
  { word: "Table Cell", pronunciation: "Têi-bel Sél", meaning: "Célula individual de uma tabela HTML" },
  { word: "Attribute", pronunciation: "É-tri-biút", meaning: "Configuração adicional aplicada em tags HTML" },
  { word: "ID", pronunciation: "Ái-Dí", meaning: "Identificador único de um elemento HTML" },
  { word: "Selector", pronunciation: "Si-lék-ter", meaning: "Padrão usado para selecionar elementos no CSS" },
  { word: "Universal Selector", pronunciation: "iú-ni-vêr-sel Si-lék-ter", meaning: "Seletor CSS que seleciona todos os elementos" },
  { word: "Property", pronunciation: "Pró-per-ti", meaning: "Característica visual configurável no CSS" },
  { word: "Value", pronunciation: "Vé-liú", meaning: "Valor atribuído a uma propriedade CSS" },
  { word: "Color", pronunciation: "Kâ-ler", meaning: "Cor aplicada em textos, fundos ou bordas" },
  { word: "Background", pronunciation: "Bék-ground", meaning: "Plano de fundo visual de um elemento" },
  { word: "Width", pronunciation: "Uídth", meaning: "Largura de um elemento HTML" },
  { word: "Height", pronunciation: "Ráit", meaning: "Altura de um elemento HTML" },
  { word: "Position", pronunciation: "Po-zí-shen", meaning: "Define posicionamento visual de elementos" },
  { word: "Relative", pronunciation: "Ré-le-tiv", meaning: "Posicionamento relativo à posição original do elemento" },
  { word: "Absolute", pronunciation: "Éb-so-lút", meaning: "Posicionamento relativo ao elemento pai posicionado" },
  { word: "Fixed", pronunciation: "Fíkst", meaning: "Posicionamento fixo na janela do navegador" },
  { word: "Sticky", pronunciation: "Stí-ki", meaning: "Posicionamento que fixa elemento durante scroll" },
  { word: "Animation", pronunciation: "Ê-ni-mêi-shen", meaning: "Movimentação visual criada com CSS" },
  { word: "Keyframes", pronunciation: "Kéi-frêims", meaning: "Etapas definidas de uma animação CSS" },
  { word: "Inline Style", pronunciation: "Ín-láin Stáil", meaning: "CSS aplicado diretamente na tag HTML" },
  { word: "External CSS", pronunciation: "Êks-têr-nel Sí-És-És", meaning: "Arquivo CSS separado conectado ao HTML" },
  { word: "Internal CSS", pronunciation: "Ín-têr-nel Sí-És-És", meaning: "CSS escrito dentro da tag style no HTML" },
  { word: "VS Code", pronunciation: "Ví-És Kôd", meaning: "Editor de código da Microsoft amplamente usado no desenvolvimento web" },
  { word: "Visual Studio", pronunciation: "Ví-ju-el Stú-di-o", meaning: "IDE completa da Microsoft para desenvolvimento de software" },
  { word: "Windsurf", pronunciation: "Uínd-sârf", meaning: "Editor de código com foco em desenvolvimento assistido por IA" },
  { word: "Zed", pronunciation: "Zéd", meaning: "Editor de código moderno focado em colaboração e performance" },
  { word: "Sublime Text", pronunciation: "Sâb-laim Tékst", meaning: "Editor de código leve e rápido para múltiplas linguagens" },
  { word: "Notepad++", pronunciation: "Nôt-péd Plâs Plâs", meaning: "Editor de texto avançado popular entre programadores Windows" },
  { word: "WebStorm", pronunciation: "Uéb-Stórm", meaning: "IDE da JetBrains especializada em JavaScript e frontend" },
  { word: "IntelliJ IDEA", pronunciation: "Ín-te-li-Djéi Ái-Dí-Í", meaning: "IDE poderosa da JetBrains voltada para Java e múltiplas linguagens" },
  { word: "PyCharm", pronunciation: "Pái-Chárm", meaning: "IDE da JetBrains especializada em desenvolvimento Python" },
  { word: "PhpStorm", pronunciation: "Pí-Éitch-Pí Stórm", meaning: "IDE da JetBrains focada em desenvolvimento PHP" },
  { word: "Android Studio", pronunciation: "Én-droid Stú-di-o", meaning: "IDE oficial do Google para desenvolvimento Android" },
  { word: "Xcode", pronunciation: "Éks-Kôd", meaning: "IDE oficial da Apple para desenvolvimento iOS e macOS" },
  { word: "CodeSandbox", pronunciation: "Kôd Sénd-bóks", meaning: "Ambiente online para desenvolvimento e testes rápidos frontend" },
  { word: "StackBlitz", pronunciation: "Stéck-Blíts", meaning: "Editor online focado em projetos web modernos" },
  { word: "Replit", pronunciation: "Ré-plit", meaning: "Plataforma online para programar e executar código no navegador" },
  { word: "GitHub Codespaces", pronunciation: "Guít-hâb Kôd-spêi-ses", meaning: "Ambiente de desenvolvimento online integrado ao GitHub" },
  { word: "CodePen", pronunciation: "Kôd-Pén", meaning: "Plataforma online para testar HTML, CSS e JavaScript rapidamente" },
  { word: "JSFiddle", pronunciation: "Djéi-És Fí-del", meaning: "Editor online para experimentos rápidos com JavaScript" },
  { word: "Glitch", pronunciation: "Glítch", meaning: "Plataforma para criar e hospedar apps web colaborativamente" },
  { word: "Command Line", pronunciation: "Ko-mánd Láin", meaning: "Forma textual de interagir com sistema operacional" },
  { word: "Shell", pronunciation: "Shél", meaning: "Programa que interpreta comandos digitados no terminal" },
  { word: "PowerShell", pronunciation: "Páu-er Shél", meaning: "Shell avançado da Microsoft para automação e administração" },
  { word: "iTerm", pronunciation: "Ái-Têrm", meaning: "Terminal avançado popular entre desenvolvedores macOS" },
  { word: "Hyper", pronunciation: "Hái-per", meaning: "Terminal moderno customizável baseado em tecnologias web" },
  { word: "Oh My Zsh", pronunciation: "Ô Mái Zí-Ésh", meaning: "Framework para personalização do terminal Zsh" },
  { word: "GitHub Desktop", pronunciation: "Guít-hâb Désk-tóp", meaning: "Aplicativo visual para gerenciamento de repositórios Git" },
  { word: "Insomnia", pronunciation: "In-sóm-ni-a", meaning: "Cliente REST usado para testes e depuração de APIs" },
  { word: "Figma", pronunciation: "Fíg-me", meaning: "Ferramenta colaborativa de design de interfaces e prototipação" },
  { word: "Adobe XD", pronunciation: "A-dô-bi Éks-Dí", meaning: "Ferramenta de design UI/UX da Adobe" },
  { word: "Canva", pronunciation: "Kén-ve", meaning: "Ferramenta online de design gráfico simplificado" },
  { word: "Chrome DevTools", pronunciation: "Krôm Dév-Túls", meaning: "Ferramentas do navegador Chrome para inspeção e depuração web" },
  { word: "Lighthouse", pronunciation: "Láit-ráus", meaning: "Ferramenta do Google para auditoria de performance web" },
  { word: "Firebase Studio", pronunciation: "Fái-er-bêis Stú-di-o", meaning: "Ambiente do Google para gerenciamento de apps Firebase" },
  { word: "Project IDX", pronunciation: "Pró-djekt Ái-Dí-Éks", meaning: "IDE online experimental do Google baseada em nuvem" },
  { word: "Gemini Code Assist", pronunciation: "Djé-mi-nai Kôd Ê-síst", meaning: "Assistente de programação com IA do Google" },
  { word: "Copilot", pronunciation: "Kô-pái-let", meaning: "Assistente de código com IA desenvolvido pelo GitHub" },
  { word: "Claude Code", pronunciation: "Klód Kôd", meaning: "Ferramenta de assistência em programação baseada em IA Claude" },
  { word: "ChatGPT", pronunciation: "Tchét-Djí-Pí-Tí", meaning: "Assistente de IA usado para programação, estudos e automação" },
  { word: "Vercel", pronunciation: "Vêr-sel", meaning: "Plataforma moderna para deploy de aplicações frontend" },
  { word: "Netlify", pronunciation: "Nét-li-fái", meaning: "Plataforma de hospedagem e deploy contínuo para sites estáticos" },
  { word: "Railway", pronunciation: "Rêil-uêi", meaning: "Plataforma simplificada para deploy de aplicações backend" },
  { word: "Render", pronunciation: "Rên-der", meaning: "Serviço de hospedagem cloud para aplicações e bancos de dados" },
  { word: "Supabase", pronunciation: "Sú-pa-bêis", meaning: "Backend open source com banco, auth e APIs integradas" },
  { word: "PlanetScale", pronunciation: "Plé-net Skêil", meaning: "Banco de dados MySQL serverless escalável" },
  { word: "Neon", pronunciation: "Ní-on", meaning: "Banco PostgreSQL serverless moderno focado em cloud" },
];
